blank_issues_enabled: true
contact_links:
  - name: Documentación / Documentation
    url: https://cyansaju-sys.github.io/tutti/documentacion.html
    about: Quizá ya esté explicado / It may already be explained
